name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_flags:
          - "-XX:+UseG1GC"
          - "-XX:+UnlockDiagnosticVMOptions"
          - "-XX:+PrintGCDetails"
          - "-XX:+PrintCompilation"
          - "-XX:+HeapDumpOnOutOfMemoryError"
          
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Set Maven Options
      run: echo "MAVEN_OPTS=${{ matrix.jvm_flags }}" >> $GITHUB_ENV
      
    - name: Build and Test with Maven
      timeout-minutes: 15
      run: ./mvnw -B verify

    - name: Get JaCoCo Coverage
      id: coverage  
      run: |
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
        echo "COVERAGE=$coverage" >> $GITHUB_ENV

    - name: Log Current JVM Flag and Coverage
      run: |
        echo "Running with JVM flag: ${{ matrix.jvm_flags }}"
        echo "Coverage for flag '${{ matrix.jvm_flags }}': $COVERAGE%"

    - name: Fail if coverage has not improved.
      run: |
        coverage=${{ env.COVERAGE }}
        threshold=24.46
        if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
          echo "Coverage is not improved."
          exit 1
        else
          echo "New coverage: $coverage%. Coverage is improved!"
        fi
